version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: runMain --args="12:00 PM -1"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: test
